version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    depends_on:
      - db
    volumes:
      - ./src:/usr/src/app
      - ./files:/usr/src/app/files
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
    networks:
      - challenge

  db:
    image: postgres:12
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - challenge

networks:
  challenge:

volumes:
  db_data: