version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    volumes:
      - ./src:/usr/src/app
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: postgres

  db:
    image: postgres:12
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

volumes:
  db_data:
